# hugo server --minify --themesDir ../.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://example.com/'
title = 'Stretch'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = false

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory

[menu]

  [[menu.streches]]
    identifier = "stretches"
    name = "Stretches"
    url = "/stretches/"
    weight = 1

  [[menu.strengthening]]
    identifier = "strengthening"
    name = "Strengthening"
    url = "/strengthening/"
    weight = 2

[params]

BookTheme = 'auto'

BookSection = '*'